-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 23:49:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdunab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdunab` ;

-- -----------------------------------------------------
-- Schema bdunab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdunab` DEFAULT CHARACTER SET utf8 ;
USE `bdunab` ;

-- -----------------------------------------------------
-- Table `bdunab`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`categorias` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`categorias` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`marcas` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`marcas` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`productos` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`productos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `impuesto` DOUBLE NULL,
  `cant_min` DOUBLE NULL COMMENT 'cantidad minima',
  `puntos` DOUBLE NULL,
  `stock` DOUBLE NULL,
  `categorias_id` INT NOT NULL,
  `marcas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productos_categorias1_idx` (`categorias_id` ASC),
  INDEX `fk_productos_marcas1_idx` (`marcas_id` ASC),
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `bdunab`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_marcas1`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `bdunab`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`roles` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`roles` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`ciudades` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`ciudades` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`clientes` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`clientes` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `puntos` DOUBLE NULL,
  `saldo` DOUBLE NULL,
  `sesion` VARCHAR(45) NULL,
  `cupo` VARCHAR(45) NULL,
  `cuotas` DOUBLE NULL,
  `roles_id` INT NOT NULL,
  `ciudades_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_roles1_idx` (`roles_id` ASC),
  INDEX `fk_clientes_ciudades1_idx` (`ciudades_id` ASC),
  CONSTRAINT `fk_clientes_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `bdunab`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_ciudades1`
    FOREIGN KEY (`ciudades_id`)
    REFERENCES `bdunab`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`tiendas` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`tiendas` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `coordenadas` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `ciudades_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tiendas_ciudades1_idx` (`ciudades_id` ASC),
  CONSTRAINT `fk_tiendas_ciudades1`
    FOREIGN KEY (`ciudades_id`)
    REFERENCES `bdunab`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`domiciliarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`domiciliarios` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`domiciliarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`rango_entregas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`rango_entregas` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`rango_entregas` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`tarifa_envios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`tarifa_envios` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`tarifa_envios` (
  `id` INT NOT NULL,
  `despcripcion` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  `cant_min` DOUBLE NULL,
  `cant_max` DOUBLE NULL,
  `precio_min` DOUBLE NULL,
  `precio_max` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`pedidos` (
  `id` INT NOT NULL,
  `fecha` DATE NULL,
  `costo_envio` DOUBLE NULL,
  `pago_entrega` DOUBLE NULL,
  `total_pedido` DOUBLE NULL,
  `total_impuesto` DOUBLE NULL,
  `total_descuento` DOUBLE NULL,
  `estado` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `calificacion` INT NULL,
  `tipo_entrega` VARCHAR(45) NULL COMMENT 'domicilio\nrecoje en la tienda\n',
  `clientes_id` INT NOT NULL,
  `tiendas_id` INT NOT NULL,
  `domiciliarios_id` INT NOT NULL,
  `rango_entregas_id` INT NOT NULL,
  `tarifa_envios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC),
  INDEX `fk_pedidos_tiendas1_idx` (`tiendas_id` ASC),
  INDEX `fk_pedidos_domiciliarios1_idx` (`domiciliarios_id` ASC),
  INDEX `fk_pedidos_rango_entregas1_idx` (`rango_entregas_id` ASC),
  INDEX `fk_pedidos_tarifa_envios1_idx` (`tarifa_envios_id` ASC),
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `bdunab`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_tiendas1`
    FOREIGN KEY (`tiendas_id`)
    REFERENCES `bdunab`.`tiendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_domiciliarios1`
    FOREIGN KEY (`domiciliarios_id`)
    REFERENCES `bdunab`.`domiciliarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_rango_entregas1`
    FOREIGN KEY (`rango_entregas_id`)
    REFERENCES `bdunab`.`rango_entregas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_tarifa_envios1`
    FOREIGN KEY (`tarifa_envios_id`)
    REFERENCES `bdunab`.`tarifa_envios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`detalle_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`detalle_pedidos` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`detalle_pedidos` (
  `id` INT NOT NULL,
  `cantidad` DOUBLE NULL,
  `precio` DOUBLE NULL,
  `impuesto` DOUBLE NULL,
  `descuento` DOUBLE NULL,
  `puntos` DOUBLE NULL,
  `pedidos_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_pedidos_pedidos_idx` (`pedidos_id` ASC),
  INDEX `fk_detalle_pedidos_productos1_idx` (`productos_id` ASC),
  CONSTRAINT `fk_detalle_pedidos_pedidos`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `bdunab`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedidos_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `bdunab`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`medio_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`medio_pagos` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`medio_pagos` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`comentario_prods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`comentario_prods` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`comentario_prods` (
  `id` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `productos_id` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `productos_id`),
  INDEX `fk_comentario_prods_productos1_idx` (`productos_id` ASC),
  INDEX `fk_comentario_prods_clientes1_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_comentario_prods_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `bdunab`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_prods_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `bdunab`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`promociones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`promociones` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`promociones` (
  `id` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  `fecha_final` DATE NULL,
  `fecha_inicial` DATE NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `productos_id`),
  INDEX `fk_promociones_productos1_idx` (`productos_id` ASC),
  CONSTRAINT `fk_promociones_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `bdunab`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`conversiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`conversiones` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`conversiones` (
  `id` INT NOT NULL,
  `cant_min` DOUBLE NULL,
  `cant_max` DOUBLE NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`pago_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`pago_pedidos` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`pago_pedidos` (
  `id` INT NOT NULL,
  `valor_pago` DOUBLE NULL,
  `medio_pagos_id` INT NOT NULL,
  `pedidos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pago_pedidos_medio_pagos1_idx` (`medio_pagos_id` ASC),
  INDEX `fk_pago_pedidos_pedidos1_idx` (`pedidos_id` ASC),
  CONSTRAINT `fk_pago_pedidos_medio_pagos1`
    FOREIGN KEY (`medio_pagos_id`)
    REFERENCES `bdunab`.`medio_pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `bdunab`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdunab`.`pqrsd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdunab`.`pqrsd` ;

CREATE TABLE IF NOT EXISTS `bdunab`.`pqrsd` (
  `id` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `pedidos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pqrsd_pedidos1_idx` (`pedidos_id` ASC),
  CONSTRAINT `fk_pqrsd_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `bdunab`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
